version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Specify the Node.js version to use

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Checkout the code from the repository

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Build project
          command: npm run build

      - store_artifacts:
          path: build/
          destination: build

      - run:
          name: Notify on success
          command: echo "Build and tests passed successfully."

      - run:
          name: Notify on failure
          command: echo "Build or tests failed."

workflows:
  version: 2
  build:
    jobs:
      - build
